import { neon } from "@neondatabase/serverless";

export const initialItems: [string, string][] = [
  ["UHT Milk 1L", "Kitchen"], ["Milk Powder 1Kg", "Kitchen"], ["Brown Sugar 1Kg", "Kitchen"],
  ["Ginger Tea (20 Tea Bags)", "Kitchen"], ["Nescafe 200g", "Kitchen"], ["Black Tea (50 Tea Bags)", "Kitchen"],
  ["Normal Green Tea (20 Tea Bags)", "Kitchen"], ["Mint Tea (20 Tea Bags)", "Kitchen"], ["Cinnamon Tea (20 Tea Bags)", "Kitchen"],
  ["Facial Tissue Boxes 100s", "Cleaning"], ["Sponge", "Cleaning"], ["Air Freshener Cinnamon 500ml", "Cleaning"],
  ["Harpic", "Cleaning"], ["Toilet Paper Roll", "Cleaning"], ["Vim Liquid - 500ml", "Cleaning"],
  ["Collin", "Cleaning"], ["Lysol Pine 950ML", "Cleaning"], ["Pynol", "Cleaning"],
  ["Harischandra Coffee 200g", "Kitchen"], ["Hand Sanitizer 500 ML", "Cleaning"],
  ["Vitamin C 500Mg", "Medical"], ["Omeprazole 20Mg", "Medical"], ["Samahan 4g", "Medical"],
  ["Sanitary Napkins (16 units)", "Medical"], ["Garbage Bags XXXL", "Cleaning"],
  ["AA Batteries", "Other"], ["AAA Batteries", "Other"], ["Mefen 500mg Tablets", "Medical"],
  ["Diagene Cards", "Medical"], ["Eno Sachets", "Medical"], ["Panadol Box", "Medical"],
  ["Jeewani Sachets", "Medical"], ["Head Fast Idoex", "Medical"], ["Idoex", "Medical"],
  ["Siddhalepa", "Medical"], ["Morteen Coil", "Cleaning"], ["Hand Wash Refill Pack", "Cleaning"],
  ["Dettol 750ML", "Cleaning"],
];

export function getDb() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is not configured.");
  return neon(connectionString);
}

let schemaReady: Promise<void> | undefined;

export function ensureSchema() {
  if (!schemaReady) {
    schemaReady = (async () => {
      const sql = getDb();
      await sql`CREATE TABLE IF NOT EXISTS items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        category TEXT NOT NULL DEFAULT 'Other',
        quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
        reorder_at INTEGER NOT NULL DEFAULT 1 CHECK (reorder_at >= 0),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`;
      await sql`CREATE TABLE IF NOT EXISTS movements (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_id INTEGER NOT NULL REFERENCES items(id),
        type TEXT NOT NULL CHECK (type IN ('issued', 'received')),
        quantity INTEGER NOT NULL CHECK (quantity > 0),
        person TEXT NOT NULL DEFAULT '',
        note TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )`;
      const values = initialItems.map((_, i) => `($${i * 2 + 1}, $${i * 2 + 2})`).join(", ");
      await sql.query(`INSERT INTO items (name, category) VALUES ${values} ON CONFLICT (name) DO NOTHING`, initialItems.flat());
    })().catch((error) => {
      schemaReady = undefined;
      throw error;
    });
  }
  return schemaReady;
}

export function errorResponse(error: unknown) {
  console.error(error);
  return Response.json({ error: "Could not save inventory right now. Please try again." }, { status: 500 });
}

export function positiveInt(value: unknown) {
  const n = Number(value);
  return Number.isSafeInteger(n) && n > 0 ? n : null;
}
